version: '1'

services:
  db:
    container_name: db
    hostname: db
    image: postgres:12
    ports:
      - ${DATABASE_PORT:-5432}:5432
    environment:
      - POSTGRES_PASSWORD ={DATABASE_PASSWORD:-pass}
      - POSTGRES_USER ={DATABASE_USER:-user}
      - POSTGRES_DB ={DATABASE_NAME:-db}
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
      - /tmp:/tmp 